[2024-12-02T06:11:07.289+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-02T06:11:07.296+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 01_unschedulled.fetch_events manual__2024-12-02T06:11:05.855938+00:00 [queued]>
[2024-12-02T06:11:07.298+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 01_unschedulled.fetch_events manual__2024-12-02T06:11:05.855938+00:00 [queued]>
[2024-12-02T06:11:07.298+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-02T06:11:07.303+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): fetch_events> on 2024-12-02 06:11:05.855938+00:00
[2024-12-02T06:11:07.306+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=143) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-02T06:11:07.306+0000] {standard_task_runner.py:72} INFO - Started process 144 to run task
[2024-12-02T06:11:07.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', '01_unschedulled', 'fetch_events', 'manual__2024-12-02T06:11:05.855938+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/website_events.py', '--cfg-path', '/tmp/tmpzlz8yb9k']
[2024-12-02T06:11:07.307+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask fetch_events
[2024-12-02T06:11:07.329+0000] {task_command.py:467} INFO - Running <TaskInstance: 01_unschedulled.fetch_events manual__2024-12-02T06:11:05.855938+00:00 [running]> on host 5b399ecdbb69
[2024-12-02T06:11:07.356+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='01_unschedulled' AIRFLOW_CTX_TASK_ID='fetch_events' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T06:11:05.855938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-02T06:11:05.855938+00:00'
[2024-12-02T06:11:07.356+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-02T06:11:07.357+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-02T06:11:07.357+0000] {logging_mixin.py:190} INFO - Current task name:fetch_events state:running start_date:2024-12-02 06:11:07.296609+00:00
[2024-12-02T06:11:07.357+0000] {logging_mixin.py:190} INFO - Dag name:01_unschedulled and current dag run status:running
[2024-12-02T06:11:07.357+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-02T06:11:07.357+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-02T06:11:07.358+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'curl -o /data/events/events.json http://events-api:5001/events']
[2024-12-02T06:11:07.362+0000] {subprocess.py:99} INFO - Output:
[2024-12-02T06:11:07.366+0000] {subprocess.py:106} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-12-02T06:11:07.366+0000] {subprocess.py:106} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-12-02T06:11:07.404+0000] {subprocess.py:106} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: events-api
[2024-12-02T06:11:07.404+0000] {subprocess.py:110} INFO - Command exited with return code 6
[2024-12-02T06:11:07.408+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2024-12-02T06:11:07.410+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-02T06:11:07.410+0000] {logging_mixin.py:190} INFO - Task start:2024-12-02 06:11:07.296609+00:00 end:2024-12-02 06:11:07.410127+00:00 duration:0.113518
[2024-12-02T06:11:07.410+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): fetch_events> dag:<DAG: 01_unschedulled> dagrun:<DagRun 01_unschedulled @ 2024-12-02 06:11:05.855938+00:00: manual__2024-12-02T06:11:05.855938+00:00, state:running, queued_at: 2024-12-02 06:11:05.861722+00:00. externally triggered: True>
[2024-12-02T06:11:07.410+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 6.
[2024-12-02T06:11:07.410+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=01_unschedulled, task_id=fetch_events, run_id=manual__2024-12-02T06:11:05.855938+00:00, execution_date=20241202T061105, start_date=20241202T061107, end_date=20241202T061107
[2024-12-02T06:11:07.414+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-02T06:11:07.414+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 31 for task fetch_events (Bash command failed. The command returned a non-zero exit code 6.; 144)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2024-12-02T06:11:07.449+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-02T06:11:07.458+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-02T06:11:07.460+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
